### ISSUE TITLE
Display nice error pages

### ISSUE THREAD

**Issue by GeertJohan** [niemeyer/gopkg#10]
Error pages should display more information.
For instance, once a package has created a version branch, the pkg.v0 will be invalidated. Right now this is displayed as: 
`GitHub repository at https://github.com/go-yaml/yaml has no branch or tag "v0", "v0.N" or "v0.N.M"`
This could be a page explaining that the package might have launched it's firsts version. e.g.:
`Maybe this package was released under a stable version number. Try <a>pkg.v1</a>`

Also; it wouldn't hurt to have all errors in the same styling as the home and pkg page. We could do this by creating a generic "error" page.

If you agree, I'm willing to start working on it.

**Comment by niemeyer** [comment]
Sorry for never jumping on this. Never had the time, and it's time to stop pretending I'll have it anytime soon.

**Comment by GeertJohan** [comment]
Hi @niemeyer , no worries, that happens :)
