### ISSUE TITLE
Fetch list of available versions

### ISSUE THREAD

**Issue by tylerstillwater** [niemeyer/gopkg#12]
I'd like to get able to ask gopkg.in for available versions of a package.

For example, I do a `GET gopkg.in/stretchr/graceful.vlist` or similar, and I receive a JSON (or otherwise) response containing a list of all available versions for this repository.

This would be useful for tools. For example:
1. A tool to insert the appropriate, latest version (or show you a list), import for a package
2. A tool to scan your project for `gopkg.in` imports and inform of new releases
3. A tool to scan your project and inform you of imports that can be changed to `gopkg.in`
4. A tool to, on save, inform you of imports that can be converted to `gopkg.in` imports

Effectively the goal is to make it easy to discover and use `gopkg.in` import paths for packages, hopefully encouraging developers to use it more.

**Comment by niemeyer** [comment]
Cleaning up the pending-and-never-done queue.
