### ISSUE TITLE
Source code links on godoc.org pages

### ISSUE THREAD

**Issue by cookieo9** [niemeyer/gopkg#13]
GoDoc.org (like godoc) provides links in the documentation to the source code when the viewer clicks on the function name.

For code hosted on the major sites (github, bitbucket, google code) the links are present and work correctly, but no links are present on gopkg.in packages.

**Comment by shellscape** [comment]
@niemeyer I know this one is _just a bit_ old, but curious if you ever made headway on how to grab the source code uri from a vanity path for a package.

**Comment by niemeyer** [comment]
No, never looked into this, sorry. :(
