### ISSUE TITLE
Self hosted

### ISSUE THREAD

**Issue by alexkappa** [niemeyer/gopkg#16]
Hi @niemeyer,

This is not an issue, more of a question really. Is there any plan to add support for self hosted deployments. It would be really cool if we can use this tool internally. I was reading through the code, and I suppose to do such a thing would be quite doable, for the most part it's about replacing "gopkg.in" with a variable (perhaps flag) and other such values which are now hard coded.

Would you be accepting pull requests for these additions? Do you have any guidelines or recommendations for contributing?

Thanks,
Alex

**Comment by elithrar** [comment]
Although this is a very old issue, you could potentially tackle it by using template tags - e.g.:

* The public gopkg.in matches on `gopkg.in/{{.github.username}}/{{.repository}}` or `gopkg.in/go-{{.repository}}/{{.repository}}`
* Self-hosted instances could accept CLI options (or env vars, a config file, etc) that allows you to specify the base domain and default username (to use if unspecified). This would support things like `project.io/pkg.v1` 
* Template tags could be used to specify a URL format other than the default - e.g. `{{domain}}/{{github.username}}/{{reponame}}.{{rev}}` could become `{{domain}}/{{rev}}/{{reponame}}` (e.g. project.io/v1/pkg) when configured with a default username.

I'd be happy to do the legwork on this if the design is agreeable.
