### ISSUE TITLE
respect canonical import paths

### ISSUE THREAD

**Issue by willnorris** [niemeyer/gopkg#30]
As you know, go1.4 will allow developers to specify the [canonical import path](https://golang.org/s/go14customimport) that should be used for importing a package.  For packages that include this, gopkg should not recommend using a gopkg import path.

For example, the appengine library uses an import path of [google.golang.org/appengine](https://github.com/golang/appengine/blob/d510d6ed93fd783ecc245231ec6a839b282a1343/appengine.go#L9).  However, if you were to navigate to http://gopkg.in/golang/appengine.v0, you would be instructed to use an import path of `gopkg.in/golang/appengine.v0`, which is clearly wrong and won't be allowed by the go command.

Instead, if gopkg detects that a package is using a canonical import path, it should display some kind of message to the effect of:

> This package uses the canonical import path `example.com/foo` and therefore cannot be used with gopkg.  
> 
> Using gopkg is great because it supports features X, Y, and Z.  Feel free to contact the developer of package foo and tell them why they should use it.  In the meantime, you can get this package using:
> 
> ```
> go get example.com/foo
> ```
> 
> and import this package using:
> 
> ```
> import "example.com/foo"
> ```

To be clear, I think using this as a place to promote the benefits of gopkg is totally fine, but it should still respect the developer's declared import path.

**Comment by niemeyer** [comment]
Way too late (sorry), but there was no bug here. The way gopkg.in has always worked was to have it as the actual canonical import path.
