### ISSUE TITLE
git clone stats

### ISSUE THREAD

**Issue by mcuadros** [niemeyer/gopkg#34]
Since gopkg is making a MitM between the real repository and the clients, we can track the number of clones and some other cool metrics. I will love know a bit more about how often are my packages used.

Caveats:
The bad part of this is that for keep the stats the service will require storage.

I can work in this feature if fits on the project scope.

**Comment by GeertJohan** [comment]
I like this idea :+1: 

One of the first things I thought about was stats as (de-) motivation. When someone publishes their fancy new project and it gets only 10 clones in the first week, that can be extremely de-motivating and lead to that person quiting the project. Even though the project could become the next `gorilla/mux` or `codegangsta/cli`. Maybe take the same approach Google Play Store does and (at first?) only display: "1-100", "100-200", "200-500", etc.

If the stats are only a simple counter without a timeline, the storage can probably kept at just a few MB's. In that case it could be as simple as a leveldb with in-memory counters and a lifetime timeout to store+remove unused counters from memory. Another interesting part will be probably be sharing the counter stats with the fail-over server.

When keeping/displaying historical stats, I can recommend InfluxDB. It provides cool options to automatically keep stats for, lets say, 24h@5m, 7d@1h, 1month@1d, ever@1week. The InfluxDB should be running on an external server and influx downtime should not lead to interrupted availability or downgraded performance at gopkg.in, just drop the stats. Maybe we could ask the InfluxDB to sponsor a hosted node. Rendering of graphs can be done client-side.

**Comment by mcuadros** [comment]
Actually is pretty similar to the Github stats:
![screen shot 2015-04-01 at 13 17 31](https://cloud.githubusercontent.com/assets/1573114/6939902/7cac5650-d871-11e4-8c4c-3a960db02c44.png)

About leveldb, personally I prefer boltdb because is pure Go, since InfluxDB needs to be a external service is getting more complex to deploy.

**Comment by niemeyer** [comment]
The Github stats should still work with gopkg.in:

 https://github.com/go-mgo/mgo/graphs/traffic

**Comment by mcuadros** [comment]
This URL is private.

**Comment by GeertJohan** [comment]
Yes github stats only works for projects you own, afaik.

**Comment by GeertJohan** [comment]
@mcuadros It doesn't **need** to be an external service, it would just be preferable to locate the db on a different machine so it can't cause any service degredation for gopkg.in. [goleveldb](http://godoc.org/github.com/syndtr/goleveldb) is also pure go.

**Comment by niemeyer** [comment]
The initial problem statement was _"I will love know a bit more about how often are my packages used"_ which as I understand it is covered by the github stats?

**Comment by GeertJohan** [comment]
@niemeyer Right. but what about public stats?

**Comment by mcuadros** [comment]
@niemeyer maybe we can change it to: I will love know a bit more about how often are my packages used and let the people see it.

We can build a badge with the downloads or something similar. But maybe this is out of the scope of this project.

**Comment by niemeyer** [comment]
I'm not sure it's worth it.. the person most interested in usage stats is the author, which is how we got here, and that's covered. Offering public usage stats then gets us into the trouble of "what if I don't want usage stats for my package to be known"? Doesn't seem worthwhile, but I can be proven wrong of course.

**Comment by mcuadros** [comment]
All the mayor index repositories includes a stats module, in  many of this cased you can put on your markdown a badge with the stats. So looks like something interesting.
Why someone wants to hide this stats?

npmjs:
![screen shot 2015-04-01 at 16 12 52](https://cloud.githubusercontent.com/assets/1573114/6942782/159180bc-d88a-11e4-83b7-3345dc4198e9.png)
pipy:
![screen shot 2015-04-01 at 16 13 15](https://cloud.githubusercontent.com/assets/1573114/6942785/15969caa-d88a-11e4-8bb0-2423e4dc2f67.png)
rubygems:
![screen shot 2015-04-01 at 16 13 35](https://cloud.githubusercontent.com/assets/1573114/6942786/159f20a0-d88a-11e4-8618-3327feea1bde.png)

**Comment by niemeyer** [comment]
Okay, I'll reopen so we can think further about this.

**Comment by GeertJohan** [comment]
I can see the argument behind "what if I don't want usage stats for my package to be known".

What about adding support for a `Gopkg.yaml` that we fetch when the latest ref for master has changed and contains an opt-in field to enable stats. I thought about a Gopkg config file earlier but never opened an issue for it: allowing people to add a custom docs URI. There are probably more use-cases for a Gopkg.yaml file. There could be a different config for each major version. (e.g.: display stats for v1, but not for v2), gopkg.in would grab the Gopkg.yaml from the latest release for every major version.

**Comment by niemeyer** [comment]
I personally think it's not worth the trouble. It's a lot of extra logic where none exist today, just to satisfy a use case which has its most relevant aspect already covered.

**Comment by mcuadros** [comment]
Can be a flag for disable if you want (in case that anyways want to disable),

BTW the idea of gopkg.yaml can worth it in the case of the version numbers, or other extra functions and documentation URL (to change the default godoc URL), but as says @niemeyer is a new extra feature that requires a clone

**Comment by mcuadros** [comment]
ping ...

**Comment by niemeyer** [comment]
I'm coming from the future to say it was indeed not worth the trouble. :)
