### ISSUE TITLE
Expect issues with gopkg.in

### ISSUE THREAD

**Issue by pavel-odintsov** [niemeyer/gopkg#36]
Hello, folks!

I'm using your project and everything working well. I working from MacOS, CentOS 7 and everything goes smoothy.

But from one server with CentOS 7 I expected so huge issues:
```bash
git clone -v https://gopkg.in/tomb.v2
Initialized empty Git repository in /root/tomb.v2/.git/
......
```

And process hangs. 

I have traced it with strace:
```bash
strace -f -etrace=connect git clone -v https://gopkg.in/tomb.v2
Initialized empty Git repository in /root/tomb.v2/.git/
Process 166342 attached
[pid 166342] connect(3, {sa_family=AF_LOCAL, sun_path="/var/run/nscd/socket"}, 110) = -1 ENOENT (No such file or directory)
[pid 166342] connect(3, {sa_family=AF_LOCAL, sun_path="/var/run/nscd/socket"}, 110) = -1 ENOENT (No such file or directory)
[pid 166342] connect(3, {sa_family=AF_INET, sin_port=htons(53), sin_addr=inet_addr("213.133.100.100")}, 16) = 0
[pid 166342] connect(3, {sa_family=AF_INET, sin_port=htons(443), sin_addr=inet_addr("107.178.216.236")}, 16) = -1 EINPROGRESS (Operation now in progress)
Process 166343 attached
[pid 166343] +++ exited with 0 +++
[pid 166342] --- SIGCHLD {si_signo=SIGCHLD, si_code=CLD_EXITED, si_pid=166343, si_status=0, si_utime=0, si_stime=0} ---
Process 166344 attached
[pid 166342] connect(6, {sa_family=AF_INET, sin_port=htons(53), sin_addr=inet_addr("213.133.100.100")}, 16) = 0
[pid 166342] connect(6, {sa_family=AF_INET, sin_port=htons(443), sin_addr=inet_addr("107.178.216.236")}, 16) = -1 EINPROGRESS (Operation now in progress)
[pid 166342] connect(9, {sa_family=AF_INET, sin_port=htons(53), sin_addr=inet_addr("213.133.100.100")}, 16) = 0
[pid 166342] connect(9, {sa_family=AF_INET, sin_port=htons(443), sin_addr=inet_addr("192.30.252.129")}, 16) = -1 EINPROGRESS (Operation now in progress)
```

So as you can see we have issues with Git itself. 

I have checked _another_ server from another network with CentOS 6 and same Git tool version and got same issues:
```bash
git clone https://gopkg.in/tomb.v2
Initialized empty Git repository in /root/tomb.v2/.git/
....
it hangs too
```

Could you test it and fix? I could offer any debug details.

**Comment by niemeyer** [comment]
That's caused by a version of git that is too (as in 5+ years old). Can you please update it and try again?

**Comment by pavel-odintsov** [comment]
So I have used this Git version:
```bash
git --version
git version 1.7.1
```

So CentOS 6 is supported by Go language and I could not upgrade git without breaking rpm system.

Do you have any options to fix this bug? What wrong with Git 1.7 ?

**Comment by niemeyer** [comment]
Version 1.7.1 lacks the change done in https://github.com/git/git/commit/d3334d9c444a22847e7add0f60c2e4a7243c151e which was release in git 1.7.3.4 in 2010.

**Comment by pavel-odintsov** [comment]
Thanks for detailed answer!

I have used this manual http://tecadmin.net/how-to-upgrade-git-version-1-7-10-on-centos-6/ and upgraded to next version:

```bash
git --version
git version 1.7.12.4
```

So everything works pretty well.
