### ISSUE TITLE
Allow specifying v0 minor versions

### ISSUE THREAD

**Issue by serejja** [niemeyer/gopkg#39]
Hi, assume I have a library which is unstable and in v0 but still being used in several other projects. I don't want to switch major version to 1 yet as backwards incompatible changes are still being made frequently.

However I want my other library dependent projects stick to some particular v0 versions (let's say project Foo uses v0.1 and project Bar uses v0.2) and not break anytime backwards incompatible changes are introduced to the library. And as I see this is currently not possible with v0 packages (getting a message like `package gopkg.in/foo/bar.v0.2: unrecognized import path "gopkg.in/foo/bar.v0.2"`).

I understand we could switch the major version anytime breaking changes are introduced but having a library of version v13.1.5 which is not production ready is funny.

Is there a chance you start supporting minor versions for v0 projects and if so would you accept PR with such a change? Hopefully I could find some time to dig into your code and make appropriate changes.

Thanks!

**Comment by nathany** [comment]
> I understand we could switch the major version anytime breaking changes are introduced but having a library of version v13.1.5 which is not production ready is funny.

That seems like the best option right now.

> Major version zero is all about rapid development. If you're changing the API every day you should either still be in version 0.y.z or on a separate development branch working on the next major version. http://semver.org

I don't think @niemeyer is going to support fetching minor versions. It seems like you just need to decide between sticking with v0 with breaking changes being expected, or changing how you think about v1 and incrementing the major version.

Of course you could also use one of several vendoring tools like Godeps or veep to lock code down while working on v0.

**Comment by niemeyer** [comment]
Yeah, what @nathany said. :)
