### ISSUE TITLE
GoDoc cannot refresh documentation of packages that use gopkg.in 

### ISSUE THREAD

**Issue by alexcesaro** [niemeyer/gopkg#40]
I just tried refreshing the documentation of my package [Gomail](https://godoc.org/gopkg.in/gomail.v2) which use gopkg.in and GoDoc showed this error: `Error refreshing package: Internal server error.`
Whereas refreshing the documentation of [github.com/go-gomail/gomail](https://godoc.org/github.com/go-gomail/gomail) worked fine: 

So I tried refreshing mgo's documentation, and there's no error with [labix.org/v2/mgo](https://godoc.org/labix.org/v2/mgo) but I just got this error with [gopkg.in/mgo.v2](https://godoc.org/gopkg.in/mgo.v2): `Error refreshing package: Error getting package files from gopkg.in.`

**Comment by GeertJohan** [comment]
Maybe this issue should be opened at golang/gddo ?
Just http 500 doesnt say much..

**Comment by alexcesaro** [comment]
It looks like it is fixed.
