### ISSUE TITLE
Add support for packages with underscores

### ISSUE THREAD

**Issue by nickjones** [niemeyer/gopkg#41]
gopkg considers this repo an unsupported URL pattern even though the github repo exists: http://gopkg.in/nickjones/proc_box.v1.

**Comment by GeertJohan** [comment]
An underscore in a package name!?
https://blog.golang.org/package-names

**Comment by GodsBoss** [comment]
Prometheus Golang client is unobtainable, too: https://godoc.org/github.com/prometheus/client_golang

**Comment by Envek** [comment]
Also couldn't do `go get gopkg.in/prometheus/client_golang.v0`

**Comment by niemeyer** [comment]
The constraints on naming were always intentional. If a path is unobtainable, it means gopkg.in was being used as the canonical import path for the project, in which case it simply won't work well. The package authors should be on board with gopkg.in for it to be used.
