### ISSUE TITLE
Occasional EOF

### ISSUE THREAD

**Issue by broady** [niemeyer/gopkg#45]
```
https fetch failed: Get https://gopkg.in/mgo.v2?go-get=1: unexpected EOF
```

Sorry, no more details than that. I see this error occasionally.

**Comment by bbrks** [comment]
We're getting the same issue. More and more frequently. Right now it's happening constantly.

**Comment by niemeyer** [comment]
Looks like a connectivity hiccup with the backend in GitHub. Constant issues are just systems being down, though, which also happens from time to time and is very noticeable with a service that pretty much never stops serving a high volume of requests.
