### ISSUE TITLE
Consider moving away from StartCom for SSL certificate

### ISSUE THREAD

**Issue by joesis** [niemeyer/gopkg#46]
This is what happened when I disabled StartCom from the list of System Root CAs, which prevented package manager (Glide in my case) from fetching any `gopkg.in` dependencies.

![image](https://cloud.githubusercontent.com/assets/22091642/19589821/63342ec4-9723-11e6-9c19-28d2870eeeea.png)

Consider [the community's response to what WoSign and StartCom did](https://news.ycombinator.com/item?id=12582534), it's a good practice to disable them. Maybe switch to Let's Encrypt?

**Comment by sattarimaseh** [comment]
Developing API on smart phone doen't allow developer toolbar. Does moving coding through Github through Startcom provide this toolbar on blumix?

**Comment by niemeyer** [comment]
I'll have a look at enabling lets encrypt there. I'm slightly worried about the added complexity, but let's see how it goes.

**Comment by niemeyer** [comment]
This is done. Please let me know if you find any issues.

**Comment by bradleyfalzon** [comment]
I just had a failure since you've posted that message in Travis:

```
Fetching https://gopkg.in/gorp.v1?go-get=1
Parsing meta tags from https://gopkg.in/gorp.v1?go-get=1 (status code 200)
get "gopkg.in/gorp.v1": found meta tag main.metaImport{Prefix:"gopkg.in/gorp.v1", VCS:"git", RepoRoot:"https://gopkg.in/gorp.v1"} at https://gopkg.in/gorp.v1?go-get=1
gopkg.in/gorp.v1 (download)
# cd .; git clone https://gopkg.in/gorp.v1 /home/travis/gopath/src/gopkg.in/gorp.v1
Cloning into '/home/travis/gopath/src/gopkg.in/gorp.v1'...
fatal: unable to access 'https://gopkg.in/gorp.v1/': gnutls_handshake() failed: A TLS fatal alert has been received.
package gopkg.in/gorp.v1: exit status 128
```

Anyone else still having issues ?

**Comment by niemeyer** [comment]
I've observed a large number of errors about unsupported ciphers and reverted. Will figure it out and try again. Please do let me know again if you see follow up problems.

**Comment by joesis** [comment]
I see following from macOS Sierra, even with `GIT_SSL_NO_VERIFY=true` option. Anyway to bypass it?

```
Cloning into '/Users/joesis/.glide/cache/src/https-gopkg.in-redis.v3'...
fatal: unable to access 'https://gopkg.in/redis.v3/': Unknown SSL protocol error in connection to gopkg.in:-9838
```

**Comment by joesis** [comment]
I got the same even if I trusted StartCom, so it should be something else.

**Comment by niemeyer** [comment]
Does it work on your browser?  What if you try to `git clone https://gopkg.in/redis.v3` (no slash at the end)?

**Comment by niemeyer** [comment]
Note that it has been redeployed again, so it's now using RSA certificates from Let's Encrypt.

**Comment by joesis** [comment]
Thanks @niemeyer ! `git clone` and `go get` works, so it's definitely not something of the site itself.

**Comment by Backstabe** [comment]
macOS Sierra
```
go get gopkg.in/airbrake/gobrake.v2
# cd .; git clone https://gopkg.in/airbrake/gobrake.v2 /Users/aectann/golang/src/gopkg.in/airbrake/gobrake.v2
Cloning into '/Users/aectann/golang/src/gopkg.in/airbrake/gobrake.v2'...
fatal: unable to access 'https://gopkg.in/airbrake/gobrake.v2/': Unknown SSL protocol error in connection to gopkg.in:-9838
```
```
git clone https://gopkg.in/airbrake/gobrake.v2
Cloning into 'gobrake.v2'...
fatal: unable to access 'https://gopkg.in/airbrake/gobrake.v2/': Unknown SSL protocol error in connection to gopkg.in:-9838
```

**Comment by joesis** [comment]
@Backstabe What's you `git` version? https://support.cloudbees.com/hc/en-us/articles/218154647-git-Unknown-SSL-protocol-error-in-connection is a great source to check for this error.

**Comment by Backstabe** [comment]
@joesis 
git version 2.10.2
```
 git clone https://gopkg.in/airbrake/gobrake.v2
Cloning into 'gobrake.v2'...
* Couldn't find host gopkg.in in the .netrc file; using defaults
*   Trying 45.33.69.124...
* Connected to gopkg.in (45.33.69.124) port 443 (#0)
* Unknown SSL protocol error in connection to gopkg.in:-9838
* Closing connection 0
fatal: unable to access 'https://gopkg.in/airbrake/gobrake.v2/': Unknown SSL protocol error in connection to gopkg.in:-9838
```
if substitute the port manually
```
git clone https://gopkg.in:9838/airbrake/gobrake.v2
Cloning into 'gobrake.v2'...
* Couldn't find host gopkg.in in the .netrc file; using defaults
*   Trying 45.33.69.124...
* connect to 45.33.69.124 port 9838 failed: Connection refused
* Failed to connect to gopkg.in port 9838: Connection refused
* Closing connection 0
fatal: unable to access 'https://gopkg.in:9838/airbrake/gobrake.v2/': Failed to connect to gopkg.in port 9838: Connection refused
```

**Comment by niemeyer** [comment]
@joesis @Backstabe: That extra slash at the end of the URL seems suspect. Are you running this in the CLI, or is it running under some sort of IDE? Can you try in the CLI and make sure there's no slash at the end?

**Comment by Backstabe** [comment]
@niemeyer yes trailing slash suspect.  I use https://github.com/constabulary/gb in CLI
manifest file
```
{
  "importpath": "gopkg.in/airbrake/gobrake.v2",
  "repository": "https://gopkg.in/airbrake/gobrake.v2",
  "revision": "5d77bd50d083834501349f8be70197b26963674d",
  "branch": "master"
}
```
I tried run `git clone` and `go get` slash entered automatically.

**Comment by niemeyer** [comment]
Okay, that's not it then. That negative port number (-9838) seems suspect. Looks like non-initialized memory. Can you please try this explicitly:
```
git clone https://gopkg.in:443/airbrake/gobrake.v2

**Comment by Backstabe** [comment]
@niemeyer 
git clone https://gopkg.in:443/airbrake/gobrake.v2
Cloning into 'gobrake.v2'...
fatal: unable to access 'https://gopkg.in:443/airbrake/gobrake.v2/': Unknown SSL protocol error in connection to gopkg.in:-9838

**Comment by niemeyer** [comment]
@Backstabe Okay, the most likely issue is that your git client is using a deprecated SSLv2 handshake.

Can you please retry now?

**Comment by niemeyer** [comment]
@Backstabe ping

**Comment by Backstabe** [comment]
@niemeyer It's not working.

**Comment by soupdiver** [comment]
Same problem here
OS: macOS Sierra (10.12.1 (16B2555))
Git: `git version 2.10.2`

I have git and openSSL installed via `brew` and everything is up-to-date

```
go get gopkg.in/yaml.v2
# cd .; git clone https://gopkg.in/yaml.v2 /Users/felix/gocode/src/gopkg.in/yaml.v2
Cloning into '/Users/felix/gocode/src/gopkg.in/yaml.v2'...
fatal: unable to access 'https://gopkg.in/yaml.v2/': Unknown SSL protocol error in connection to gopkg.in:-9838
package gopkg.in/yaml.v2: exit status 128
```

```
git clone https://gopkg.in:443/airbrake/gobrake.v2
Cloning into 'gobrake.v2'...
fatal: unable to access 'https://gopkg.in:443/airbrake/gobrake.v2/': Unknown SSL protocol error in connection to gopkg.in:-9838
```

**Comment by Backstabe** [comment]
try
`git config --global http.sslVerify true `

**Comment by soupdiver** [comment]
@Backstabe Nice, thanks!
But why does it work with explicit ssl verification? Shouldn't verification be on by default?
