### ISSUE TITLE
Latest git does not follow redirects by default, breaking gopkg.in

### ISSUE THREAD

**Issue by mikedanese** [niemeyer/gopkg#50]
See https://github.com/kubernetes/kubernetes/issues/39583 for an example of this failure

**Comment by niemeyer** [comment]
Thanks for filing it. We'll need to change the gopkg.in implementation a bit to adapt to this.

**Comment by ixdy** [comment]
FYI, my workaround for the time being was to run
```console
$ git config --global http.https://gopkg.in.followRedirects true
```

**Comment by alecthomas** [comment]
Any way to fix this on the gopkg.in server?

**Comment by broady** [comment]
@niemeyer are you willing to proxy the contents of `git-upload-pack`?

**Comment by kyoh86** [comment]
@niemeyer are you willing to fix it???

**Comment by ajlanghorn** [comment]
Thanks for this; this helped me fix a few problems I was having installed dependencies. Now to find the fix to the rest. Would be awesome if Git would just follow 301s by default, though.

**Comment by niemeyer** [comment]
Yeah, I'll fix it. We'll need to proxy the remaining of the request through the gopkg.in server as well so git doesn't complain about it. Unfortunate, as it will increase the bandwidth requirements, but can't see another workaround given the latest git changes.

**Comment by niemeyer** [comment]
@ajlanghorn It did for several years. The very latest git decided to break that.

**Comment by netroby** [comment]
please fix it . all packages require gopkg.in broken

**Comment by ixdy** [comment]
https://github.com/git/git/commit/50d3413740d1da599cdc0106e6e916741394cc98 contains an explanation of why this change was implemented in `git`.

**Comment by niemeyer** [comment]
I have deployed a modified server version at https://p3.gopkg.in.. it would be very helpful if people here affected by this issue could give it a try and let me know whether it works properly for you and your project, and what's the timing impact compared to https://gopkg.in.

Thanks for your help.

**Comment by niemeyer** [comment]
Note you can test this with git directly, without involving the go tool:
```
$ git clone https://p3.gopkg.in/<your project>
```

**Comment by alecthomas** [comment]
Thanks @niemeyer, seems to work fine for me. Oddly, this seems faster than the original: roughly 2.5 seconds vs. 4.5 seconds. Could be load related on the server I guess? The repo's seem to be basically identical.

```bash
[aat@cavern:~/Projects/foo]time git clone https://gopkg.in/alecthomas/kingpin.v3-unstable old
Cloning into 'old'...
remote: Counting objects: 1353, done.
remote: Total 1353 (delta 0), reused 0 (delta 0), pack-reused 1353
Receiving objects: 100% (1353/1353), 403.51 KiB | 296.00 KiB/s, done.
Resolving deltas: 100% (902/902), done.
git clone https://gopkg.in/alecthomas/kingpin.v3-unstable old  0.08s user 0.07s system 3% cpu 4.721 total
[aat@cavern:~/Projects/foo]unset git
[aat@cavern:~/Projects/foo]time git clone https://p3.gopkg.in/alecthomas/kingpin.v3-unstable new
Cloning into 'new'...
remote: Counting objects: 1353, done.
remote: Total 1353 (delta 0), reused 0 (delta 0), pack-reused 1353
Receiving objects: 100% (1353/1353), 403.51 KiB | 164.00 KiB/s, done.
Resolving deltas: 100% (902/902), done.
git clone https://p3.gopkg.in/alecthomas/kingpin.v3-unstable new  0.08s user 0.07s system 5% cpu 2.589 total
[aat@cavern:~/Projects/foo]rm -rf *
[aat@cavern:~/Projects/foo]time git clone https://p3.gopkg.in/alecthomas/kingpin.v3-unstable new
Cloning into 'new'...
remote: Counting objects: 1353, done.
remote: Total 1353 (delta 0), reused 0 (delta 0), pack-reused 1353
Receiving objects: 100% (1353/1353), 403.51 KiB | 214.00 KiB/s, done.
Resolving deltas: 100% (902/902), done.
git clone https://p3.gopkg.in/alecthomas/kingpin.v3-unstable new  0.07s user 0.06s system 6% cpu 2.117 total
[aat@cavern:~/Projects/foo]time git clone https://gopkg.in/alecthomas/kingpin.v3-unstable old
Cloning into 'old'...
remote: Counting objects: 1353, done.
remote: Total 1353 (delta 0), reused 0 (delta 0), pack-reused 1353
Receiving objects: 100% (1353/1353), 403.51 KiB | 198.00 KiB/s, done.
Resolving deltas: 100% (902/902), done.
git clone https://gopkg.in/alecthomas/kingpin.v3-unstable old  0.08s user 0.07s system 3% cpu 4.512 total
```

**Comment by alecthomas** [comment]
Note that `go get` does not seem to work. I'm not sure if this is intentional at this stage.

```sh
[aat@cavern:~/Projects/foo]go get -u -v p3.gopkg.in/alecthomas/kingpin.v3-unstable
Fetching https://p3.gopkg.in/alecthomas/kingpin.v3-unstable?go-get=1
Parsing meta tags from https://p3.gopkg.in/alecthomas/kingpin.v3-unstable?go-get=1 (status code 200)
package p3.gopkg.in/alecthomas/kingpin.v3-unstable: unrecognized import path "p3.gopkg.in/alecthomas/kingpin.v3-unstable" (parse https://p3.gopkg.in/alecthomas/kingpin.v3-unstable?go-get=1: no go-import meta tags)
```

**Comment by niemeyer** [comment]
@alecthomas Thanks for the test. The difference is most likely related to networking connectivity rather than load at this instance, although in the future once we convert `gopkg.in` itself to that new logic load will definitely be a concern.

For the latter issue, indeed go get won't work out of gopkg.in because the metadata still points at `gopkg.in` itself.

**Comment by johanbrandhorst** [comment]
What is the status of this? Is there a roadmap for further deployment?

**Comment by niemeyer** [comment]
Yes, this week a percentage of repositories will start using the new logic. We'll then gradually increase until everything is behind it.

**Comment by niemeyer** [comment]
**HEADS UP:** I've just switched the DNS to a server addressing the redirect issue in the latest git.

Please shout on problems!

**Comment by niemeyer** [comment]
No reported issues and 10GB/h flowing through the system. I'm considering this issue sorted for the time being.

**Comment by vimalk78** [comment]
not able to do
`go get -v gopkg.in/kataras/iris.v6`

is there some issue

**Comment by jpwilliams** [comment]
Working okay for me, @vimalk78.

Might well be an issue with your `$GOROOT`/`$GOPATH`, but either way I'm relatively confident it's not to do with this issue.

**Comment by coolaj86** [comment]
I'm working on something similar and I'm curious to know what the technical solution was.

Was it doing the redirect in a different way? Or was it running a full proxy of the byte stream?

**Comment by paddlefish** [comment]
> ```
> git config --global http.https://gopkg.in.followRedirects true
> ```

This was not sufficient for me.

However, after I also updated `git` locally, `go get` worked again.

I'm on a Mac, I used `brew upgrade git` to install git version 2.27 (was previously 2.22.0)
