### ISSUE TITLE
go get fails with status 301

### ISSUE THREAD

**Issue by akupila** [niemeyer/gopkg#52]
run:
```
$ go get gopkg.in/yaml.v2
```

result:
```
# cd .; git clone https://gopkg.in/yaml.v2 /Users/akupila/go/src/gopkg.in/yaml.v2
Cloning into '/Users/akupila/go/src/gopkg.in/yaml.v2'...
error: RPC failed; HTTP 301 curl 22 The requested URL returned error: 301
fatal: The remote end hung up unexpectedly
package gopkg.in/yaml.v2: exit status 128
```

I suspect this could be related to the [recently added Let's Encrypt support](https://github.com/niemeyer/gopkg/commit/c70d35213a11190a3f9d921a421d4ec04620e60f). I'm not very familiar with how git clone works under the hood but some quick googling and found https://github.com/gitlabhq/gitlabhq/issues/3892

**Comment by akupila** [comment]
Sorry, looks like a duplicate of https://github.com/niemeyer/gopkg/issues/50

After `git config --global http.https://gopkg.in.followRedirects true` this works fine

**Comment by niemeyer** [comment]
No need to change the configuration anymore. We've changed gopkg.in itself to support the new git quirks.
