### ISSUE TITLE
Public Report Not Activated

### ISSUE THREAD

**Issue by rubenv** [niemeyer/gopkg#53]
There's an uptime report link on the website, but when I follow it, it tells me:
> Public Report Not Activated

**Comment by niemeyer** [comment]
Yeah, pingdom itself disabled the status report. They significantly limited the free accounts about a year ago.

**Comment by rubenv** [comment]
Would Apex Ping be a good alternative? https://apex.sh/ping/

**Comment by niemeyer** [comment]
Thanks, I'll have a look.
