### ISSUE TITLE
Failed to connect to gopkg.in port 443: Operation timed out

### ISSUE THREAD

**Issue by petermbenjamin** [niemeyer/gopkg#65]
I am not sure if this is the appropriate forum to bring up such issue, but here goes.

When I run `go get -v gopkg.in/yaml.v2` while on my corporate VPN, I get the error: `Failed to connect to gopkg.in port 443: Operation timed out`, but `go get` works just fine on my home network.

Additionally, I can't even hit https://gopkg.in on corporate VPN, but works fine on my home network.

I originally suspected my corporate VPN / strict firewall policies to be the problem, but I was able to hit a number of `*.in` domains.

I am starting to think that perhaps `gopkg.in` has blocked the egress IP address of my corporate VPN.

Any ideas?

**Comment by GeertJohan** [comment]
Would it be possible that the corporate VPN has blocked the IP for gopkg.in? Perhaps because of throughput limitations (lots of go get calls?).
