### ISSUE TITLE
cannot talk to GitHub

### ISSUE THREAD

**Issue by prabhat2486** [niemeyer/gopkg#66]
$ go get github.com/micro/go-config
package gopkg.in/yaml.v2: unrecognized import path "gopkg.in/yaml.v2" (https fetch: Get https://gopkg.in/yaml.v2?go-get=1: read tcp 10.233.243.127:52710->35.196.143.184:443: wsarecv: An existing connection was forcibly closed by the remotehost.)

**Comment by niemeyer** [comment]
The error message says exactly what happened.
