### ISSUE TITLE
Installations from gopkg.in failing

### ISSUE THREAD

**Issue by djmitche** [niemeyer/gopkg#67]
https://tools.taskcluster.net/groups/Dbxt_ZAzSdGbw4tWOmEdbw/tasks/U3tZazOITWyo5hRCpiIWmw/runs/0/logs/public%2Flogs%2Flive_backing.log

is failing with

```
go: gopkg.in/yaml.v2@v2.2.2: unrecognized import path "gopkg.in/yaml.v2" (parse https://gopkg.in/yaml.v2?go-get=1: no go-import meta tags ())
```

and has been for a few days now.

```
dustin@jemison ~ $ curl https://gopkg.in/yaml.v2?go-get=1

<html>
<head>
<meta name="go-import" content="gopkg.in/yaml.v2 git https://gopkg.in/yaml.v2">
<meta name="go-source" content="gopkg.in/yaml.v2 _ https://github.com/go-yaml/yaml/tree/v2.2.2{/dir} https://github.com/go-yaml/yaml/blob/v2.2.2{/dir}/{file}#L{line}">
</head>
<body>
go get gopkg.in/yaml.v2
</body>
</html>
```

I can't reproduce this locally, but I expect that yaml.v2 has been cached somewhere for me.

**Comment by djmitche** [comment]
I have reproduced this locally, by running `while docker run -ti --rm -e XDG_CACHE_HOME=/cache golang:1.12.9 bash -c "git clone --quiet --depth=20 --no-single-branch git://github.com/djmitche/taskcluster.git taskcluster && cd taskcluster && git checkout becb3a321d667327dec3733cd83333f698fc0c77 && cd clients/client-shell && go test -v -race ./..."; do :; done`.  I was not able to reproduce it without the XDG_CACHE_HOME, although since this seems intermittent that might have been due to random chance.

**Comment by djmitche** [comment]
Confirmed, without XDG_CACHE_HOME, after about 24 minutes of running that loop:

```
go: gopkg.in/check.v1@v1.0.0-20180628173108-788fd7840127: git fetch -f origin refs/heads/*:refs/heads/* refs/tags/*:refs/tags/* in /go/pkg/mod/cache/vcs/7e5fa1eab4705eb80c9746632736cea906708d060702d529df6241d1c8c2c9f9: exit status 128:
        remote: Cannot obtain refs from GitHub: cannot talk to GitHub: Get https://github.com/go-check/check.git/info/refs?service=git-upload-pack: dial tcp 140.82.114.3:443: socket: too many open files
        fatal: unable to access 'https://gopkg.in/check.v1/': The requested URL returned error: 502
go: gopkg.in/yaml.v2@v2.2.2: git fetch -f origin refs/heads/*:refs/heads/* refs/tags/*:refs/tags/* in /go/pkg/mod/cache/vcs/4f939cf8921e8662ef2d8cf78b0db3bcacccda0d79c9e1b4cef06c640b4a8cef: exit status 128:
        remote: Cannot obtain refs from GitHub: cannot talk to GitHub: Get https://github.com/go-yaml/yaml.git/info/refs?service=git-upload-pack: dial tcp 140.82.114.3:443: socket: too many open files
        fatal: unable to access 'https://gopkg.in/yaml.v2/': The requested URL returned error: 502
go: gopkg.in/tylerb/graceful.v1@v1.2.15: git fetch -f origin refs/heads/*:refs/heads/* refs/tags/*:refs/tags/* in /go/pkg/mod/cache/vcs/5dbbd5c546c1154051b39dc6d7b6a7d98fc7e9edd2e2d6c2e6a4dbaaee19d132: exit status 128:
        remote: Cannot obtain refs from GitHub: cannot talk to GitHub: Get https://github.com/tylerb/graceful.git/info/refs?service=git-upload-pack: dial tcp 140.82.114.3:443: socket: too many open files
        fatal: unable to access 'https://gopkg.in/tylerb/graceful.v1/': The requested URL returned error: 502
go: error loading module requirements
```

**Comment by djmitche** [comment]
This looks like a load issue at gopkg.in?

**Comment by niemeyer** [comment]
The gopkg.in server is being moved to a different data center right now, partly due to its increased usage. Bashing the server with a loop won't be very helpful for you or for others.

**Comment by kaushiknag90** [comment]
Getting this error again today while pulling dependencies from gopkg. Can you please help or suggest as this is blocking our builds, deployments.

`
go: gopkg.in/check.v1@v1.0.0-20201130134442-10cb98267c6c: unrecognized import path "gopkg.in/check.v1": reading https://gopkg.in/check.v1?go-get=1: 502 Bad Gateway
Makefile:56: recipe for target 'test' failed</span></span></body></html>
`

**Comment by RomainMuller** [comment]
Experiencing this issue again today:

```
gopkg.in/yaml.v3@v3.0.0-20200615113413-eeeca48fe776 requires
gopkg.in/check.v1@v0.0.0-20161208181325-20d25e280405: unrecognized import path "gopkg.in/check.v1": reading https://gopkg.in/check.v1?go-get=1: 502 Bad Gateway
server response: Cannot obtain refs from GitHub: cannot talk to GitHub: Get https://github.com/go-check/check.git/info/refs?service=git-upload-pack: net/http: request canceled (Client.Timeout exceeded while awaiting headers)
```

**Comment by niemeyer** [comment]
We still see issues from time to time. Some of them are just either side (Canonical or GitHub) having connectivity issues, but there's also some sort of longstanding issue which seems related to problematic caching of idle connections after some other event.  The code on gopkg itself is quite simple, though, so unless I'm missing something obvious it doesn't feel like this should persist the way it does. In either case, I've added a small attempt to workaround the issue by detecting this situation and dropping the idle connections. This has been deployed today, together with updated dependencies to bring them to recent releases. Let's see what happens next.
