### ISSUE TITLE
gopkg.in/srwiley/oksvg.gradfix does not resolve 

### ISSUE THREAD

**Issue by probonopd** [niemeyer/gopkg#72]
I would like to import  the `gradfix` branch of https://github.com/srwiley/oksvg.

`gopkg.in/srwiley/oksvg.gradfix` does not resolve to the `gradfix` branch of https://github.com/srwiley/oksvg, instead it says

> Unsupported URL pattern; see the documentation at gopkg.in for details.

Why?

Reference:
https://github.com/srwiley/oksvg/issues/15#issuecomment-576441957

**Comment by niemeyer** [comment]
The naming convention is indeed a constraint from gopkg.in itself, as the error indicates.
