### ISSUE TITLE
fatal: unable to access .* SSL certificate problem: self signed certificate in certificate chain package 

### ISSUE THREAD

**Issue by LY1806620741** [niemeyer/gopkg#73]
if you see some error stream likes ```fatal: unable to access 'https://gopkg.in/russross/blackfriday.v2/': SSL certificate problem: self signed certificate in certificate chain package gopkg.in/russross/blackfriday.v2: exit status 128```, you can try to close git sslverify by command ```git config --global http.sslVerify false``` and try it again.

**Comment by niemeyer** [comment]
No, **never ever** do that. It means you're potentially picking up your source code from an arbitrary middle man.
