### ISSUE TITLE
Cannot obtain refs from GitHub: cannot talk to GitHub

### ISSUE THREAD

**Issue by shubhamvyas-josh** [niemeyer/gopkg#79]
My builds are failing due to failure in download of dependencies from gopkg. 
-   gopkg.in/yaml.v3@v3.0.1: unrecognized import path "gopkg.in/yaml.v3": reading https://gopkg.in/yaml.v3?go-get=1: 502 Bad Gateway
- go: gopkg.in/ini.v1@v1.62.0: unrecognized import path "gopkg.in/ini.v1": reading https://gopkg.in/ini.v1?go-get=1: 502 Bad Gateway

When will it be fixed and is there any temp solution for such issue ?

**Comment by niemeyer** [comment]
Sorry about that, there was a data cente-wide issue today/yesterday:

https://status.canonical.com/

**Comment by curtismenmuir** [comment]
@niemeyer do you have an ETA for when this will be fix? Status page says `all operational` and that the issue with `gopkg.in` has 
been fixed for ~10hrs, but our CI builds have been failing all day.

**Comment by harsh-rr** [comment]
Still facing the issue even though https://status.canonical.com/ everything is fine

**Comment by curtismenmuir** [comment]
Work around for this: https://github.com/orgs/community/discussions/56932#discussioncomment-6069091

We got this working by setting the `GOPROXY` Env Var to `https://proxy.golang.org,direct` :)

EG add `GOPROXY=https://proxy.golang.org,direct` to Jenkinsfile env vars

**Comment by niemeyer** [comment]
The team confirmed they're observing issues still. They are on it. Sorry again for the trouble.
