### ISSUE TITLE
gopkg in 502

### ISSUE THREAD

**Issue by j-maltese** [niemeyer/gopkg#84]
This morning https://gopkg.in/yaml.v2 is unreachable and is returning a 502 which is causing our build pipelines to fail. This happens periodically, maybe a couple times a year. Is there alerting/monitoring for when that server becomes unreachable? This situation is usually fixed within a few hours, but I am unaware of what the resolution steps are on the gopkg side.

**Comment by j-maltese** [comment]
![Screenshot 2024-06-20 104215](https://github.com/niemeyer/gopkg/assets/52833414/d7115ebe-d52d-475e-a602-c8381f86e83b)

**Comment by niemeyer** [comment]
Thanks for reporting. There's indeed an on going issue in the data center. The team is on it.

**Comment by niemeyer** [comment]
This should have been addressed now.
