### ISSUE TITLE
How do you reference a versioned sub-package?

### ISSUE THREAD

**Issue by Quantisan** [niemeyer/gopkg#9]
For example, if `router.go` of `main` uses `trie` package in a subdir, I tried `gopkg.in/GlassyMedia/go-json-rest/trie.v1` but it doesn't seem to work. Is this feature available?

I can send in a pull request if you point me in the right direction on how to patch it.

```
├── router.go
├── router_benchmark_test.go
├── router_test.go
├── status.go
├── status_test.go
├── test
│   └── util.go
├── timer.go
└── trie
    ├── impl.go
    └── impl_test.go
```

**Comment by wwwdata** [comment]
any updates on this? If I have a package that contains multiple sub packages, which are always 100% compatible to the parent package, renaming the imports is a lot of wasted effort/time and just overhead.

**Comment by nathany** [comment]
I haven't tried gopkg.in with subpackages yet. Do you have a v1 branch with different import paths? And on every release you merge changes from master and have to update import paths or deal with conflicts?

Looking at some of the Canonical uses,mike go-aws, they don't have a mater branch at all. So they only need to change import paths when releasing a new major version. You can set your default branch to something other than master on GitHub.

**Comment by niemeyer** [comment]
This was here as a doc issue, but the links here seem to be talking about git modules?

Either way, not that "go get" works more like gopkg.in itself, seems less of a concern.
